const fs = require("fs");
const path = require("path");
const https = require("https");
const express = require("express");
const WebSocket = require("ws");

// === Load certs generated by mkcert ===
// Run: mkcert localhost 127.0.0.1 ::1
// This creates localhost.pem and localhost-key.pem
const options = {
  key: fs.readFileSync("localhost-key.pem"),
  cert: fs.readFileSync("localhost.pem"),
};

const app = express();

// === Serve static VR/Annotation files from "public" folder ===
app.use(express.static(path.join(__dirname, "public")));

const server = https.createServer(options, app);

// === WebSocket signaling ===
const wss = new WebSocket.Server({ server });

let vrClient = null;
let annotationClient = null;

wss.on("connection", (ws) => {
  ws.on("message", (msg) => {
    const data = JSON.parse(msg);
    console.log("Server got:", data.type);

    if (data.type === "register") {
      if (data.role === "vr") {
        vrClient = ws;
        console.log("✅ VR client registered");
      }
      if (data.role === "annotation") {
        annotationClient = ws;
        console.log("✅ Annotation client registered");
      }
      return;
    }

    if (data.type === "offer" && annotationClient) {
      annotationClient.send(JSON.stringify(data));
    }
    if (data.type === "answer" && vrClient) {
      vrClient.send(JSON.stringify(data));
    }
    if (data.type === "ice") {
      if (data.role === "vr" && annotationClient) annotationClient.send(JSON.stringify(data));
      if (data.role === "annotation" && vrClient) vrClient.send(JSON.stringify(data));
    }
    if (data.type === "annotation" && vrClient) {
      vrClient.send(JSON.stringify(data));
    }
  });

  ws.on("close", () => {
    if (ws === vrClient) vrClient = null;
    if (ws === annotationClient) annotationClient = null;
  });
});

server.listen(8080, () => {
  console.log("🚀 Server running at https://localhost:8080");
});
